### ISSUE TITLE
🐛 pterodactyl version is not up to date

### ISSUE THREAD

**Issue by AAWA-byt** [YoshiWalsh/docker-pterodactyl-panel#3]
![2023-04-02 15_24_50-Pterodactyl - Administration – Mozilla Firefox](https://user-images.githubusercontent.com/76434239/229355679-e0555f36-26a1-44e2-ab46-a047490166b7.png)

**Comment by YoshiWalsh** [comment]
This is fixed. Please note that you'll need to update your composer file to refer to `yoshiwalsh/pterodactyl-panel`.
